### ISSUE TITLE
文本bug报告

### ISSUE THREAD

**Issue by mitaina** [TomJinW/PKMN_GSCHS#1]
![Screenshot_2022-06-12-17-11-29-21_00aa2cb23bb9e5cf4f030f09d5f6fd3f.jpg](https://user-images.githubusercontent.com/45205701/173226158-bf244207-fe98-4100-a521-f6c326fc0e9d.jpg)

在使用头锤之类带有恐惧效果的技能之后，显示的是"xxx快要不行了"这种。😂

**Comment by ixaoce** [comment]
玩的是金0.93

**Comment by ixaoce** [comment]
![Screenshot_2022-06-12-17-33-51-25_00aa2cb23bb9e5cf4f030f09d5f6fd3f.jpg](https://user-images.githubusercontent.com/45205701/173227064-3aafccdf-6388-4127-bd4e-64e70b29232a.jpg)![Screenshot_2022-06-12-17-33-55-28_00aa2cb23bb9e5cf4f030f09d5f6fd3f.jpg](https://user-images.githubusercontent.com/45205701/173227065-6d22eb20-b495-42e9-95b3-921e421c718f.jpg)
还有自然公园的一个带雷丘的npc，一进入对战，不管怎么操作都会卡死然后如图显示

**Comment by ixaoce** [comment]
烧焦塔碎岩完全不会出精灵，测试超多次

**Comment by TomJinW** [comment]
> ![Screenshot_2022-06-12-17-11-29-21_00aa2cb23bb9e5cf4f030f09d5f6fd3f.jpg](https://user-images.githubusercontent.com/45205701/173226158-bf244207-fe98-4100-a521-f6c326fc0e9d.jpg)
> 
> 在使用头锤之类带有恐惧效果的技能之后，显示的是"xxx快要不行了"这种。😂

这个确实是本人错翻。战斗系统有些许文本存在这样的错误。这些错误都已经在下一个版本中修复。请等我测试结束后公布。

**Comment by TomJinW** [comment]
> ![Screenshot_2022-06-12-17-33-51-25_00aa2cb23bb9e5cf4f030f09d5f6fd3f.jpg](https://user-images.githubusercontent.com/45205701/173227064-3aafccdf-6388-4127-bd4e-64e70b29232a.jpg)![Screenshot_2022-06-12-17-33-55-28_00aa2cb23bb9e5cf4f030f09d5f6fd3f.jpg](https://user-images.githubusercontent.com/45205701/173227065-6d22eb20-b495-42e9-95b3-921e421c718f.jpg)
> 还有自然公园的一个带雷丘的npc，一进入对战，不管怎么操作都会卡死然后如图显示
> 这玩意我也不知道怎么整出来的。重新读了电池存档就正常了。。
> 又试了一下，第一次进自然公园从下面的门第一次进就概率出现。遇到了两三次

这个Bug是涉及到招式名称的严重错误Bug，很多NPC训练家都有概率触发。下个版本中已经修复。请等我测试结束。

**Comment by TomJinW** [comment]
> 烧焦塔碎岩完全不会出精灵，测试超多次

很遗憾目前这个问题我在原版韩版ROM中一样遇到了。似乎不是我汉化的问题。具体的情况还请等我事后分析。

**Comment by TomJinW** [comment]
玩家您好

感谢您反馈汉化版问题。
很遗憾，目前这个问题我在原版韩版ROM中一样遇到了。似乎不是我汉化的问题。具体的情况还请等我事后分析。

祝好
Tom

**Comment by ixaoce** [comment]
![Pocket Monsters Geum (Korea) (patched)_1655126604467.png](https://user-images.githubusercontent.com/45205701/173476105-f82fd386-05b5-4938-abda-b0b8550913b3.png)![Pocket Monsters Geum (Korea) (patched)_1655126608849.png](https://user-images.githubusercontent.com/45205701/173476112-a522849b-5d4d-47d7-a3c4-c53a795ca849.png)

感谢大佬。
还有浅葱市商店里一个npc对话乱码

**Comment by TomJinW** [comment]
> 

这个已在测试流程中发现。下一个版本中已修复。

**Comment by TomJinW** [comment]
> ![Pocket Monsters Geum (Korea) (patched)_1655126604467.png](https://user-images.githubusercontent.com/45205701/173476105-f82fd386-05b5-4938-abda-b0b8550913b3.png)![Pocket Monsters Geum (Korea) (patched)_1655126608849.png](https://user-images.githubusercontent.com/45205701/173476112-a522849b-5d4d-47d7-a3c4-c53a795ca849.png)
> 
> 感谢大佬。 还有浅葱市商店里一个npc对话乱码

这个已在测试流程中发现。下一个版本中已修复。感谢反馈。
