### ISSUE TITLE
显示星期

### ISSUE THREAD

**Issue by monkey7581sss888** [TomJinW/PKMN_GSCHS#2]
看图

金银版共有的神秘代码如下

0:1448

B93FC03FC73FCE3FD53FDC3FE33F

0:3FB9

01C10A8307695001C10A830AAD5001C10A8306265001C10A8304915001C10A8301AD5001C10A8309B45001C10A8301C650

![bgb00001](https://user-images.githubusercontent.com/81839885/174328678-c0355f59-e0bc-4ec1-8672-713ddf18650c.jpg)

**Comment by TomJinW** [comment]
哇塞。感谢大佬 好厉害

**Comment by TomJinW** [comment]
我确认一下这样改完之后广播节目是否能正常显示

**Comment by TomJinW** [comment]
大佬的这个思路..顺带解决了地面两个字塞不下的问题

**Comment by monkey7581sss888** [comment]
其它的问题，有空帮你慢慢看

**Comment by TomJinW** [comment]
好的，麻烦了。存档我在Release里放了个我自己玩的一个存档。以及这个repo新增了一个tmp分支，可以看到我当前的一些进展，避免重复劳动。其他的东西还有需要的话就再联系。

**Comment by TomJinW** [comment]
哦对这个星期修正有个小错误...就是列表的顺序的第一位是星期天而不是星期一

**Comment by monkey7581sss888** [comment]
文本改下星期的顺序就行了
01C10A8301C65001C10A8307695001C10A830AAD5001C10A8306265001C10A8304915001C10A8301AD5001C10A8309B450

**Comment by TomJinW** [comment]
> 文本改下星期的顺序就行了
> 01C10A8301C65001C10A8307695001C10A830AAD5001C10A8306265001C10A8304915001C10A8301AD5001C10A8309B450

哦 这个明白的，只是告诉大佬...那个Code不是很对。然后我现在照着大佬思路修复了很多只能显示小字的地方。
