### ISSUE TITLE
图鉴汉语拼音排序

### ISSUE THREAD

**Issue by monkey7581sss888** [TomJinW/PKMN_GSCHS#3]
金银共用
图鉴汉语拼音排序
10:4B66
1817A8A60CA52D5784F8AE79821110AFB0D1D2A996292C59581B1C5BE6601253D0A0F1625A6C47A25F0F9A2A164FC75073E466AA32ABEF7DB55455490D6FE889E98B7B6A3BFACD69375EA3445C5DCA94757843D6C6E53841D58C8E399D059B9C92887190BBBCBD760777EA26988AE2D4638F3A68087F3F368046956BE31483459FF31A87818D154E254B4CF90AB7B8487235A430B697C87CEE9334020301B3317A741F1D20211E22D72E2F27280664AD192423ACCBD3C1D9B4DADB3352F791FBB96E09F586DEC4B2B1CF0B0EDFEBCE6D6542A1C93D3CBA3EC2ECC0BF5156044D9E134ADCE7E1F2D8F07EF467856140F6A799C5EDE0DDBEC3CC2B70

拼音
10:47D0
05B50143拼音

![bgb00003](https://user-images.githubusercontent.com/81839885/174427650-9a549a4e-cc5a-4874-a223-cc756e30a1f0.jpg)
![bgb00002](https://user-images.githubusercontent.com/81839885/174427655-53d201a4-f32e-4c83-b2a1-d1892b3a8d29.jpg)

**Comment by TomJinW** [comment]
啊感谢 这个本人昨天刚修复完。

**Comment by TomJinW** [comment]
不难的
