### ISSUE TITLE
全图鉴的奖状

### ISSUE THREAD

**Issue by monkey7581sss888** [TomJinW/PKMN_GSCHS#4]
这几个字要改成什么？
![bgb00004](https://user-images.githubusercontent.com/81839885/174428423-3c98fa93-cf6a-4b75-b3d0-ce04dd4dd7c6.jpg)

**Comment by monkey7581sss888** [comment]
换行

**Comment by monkey7581sss888** [comment]
我需要2*10TILE
16*80像素大小的替换图片

**Comment by TomJinW** [comment]
稍等啊

**Comment by TomJinW** [comment]
[award.zip](https://github.com/TomJinW/PKMN_GSCHS/files/8934486/award.zip)
原始的bin和bmp都放在zip里了，麻烦大佬了。

**Comment by monkey7581sss888** [comment]
38:4148	1213141818242526
38:415C	151623181868696A
	
38:401D	CDB07C
	
38:7BF0	00FF00FF00FF00F100F900FF00F800F100FF00FF00390038003000230021003800FF00FF00FF001F001F009F001F003F00FF00F000F000FF00FE00E000E000FF00200000000000110038007C00FE00FF007F000F000F00FF00FF000F000F00FF00FF00FF00FE00FE00F200F200F800FE00FF00FF00790079007900790040004000FF00FF00FF003F001F009F0007000700FC00F800F200F200FE00FE00FE00FF00790070007000620047000F001F00FF00FF00FF007F003F001F008700C700FFCDE30AF5C5D5E521F07B1120910150002A12130B78B120F821407C1130920140002A12130B78B120F821807C1180960130002A12130B78B120F8E1D1C1F1C9

![bgb00006](https://user-images.githubusercontent.com/81839885/175244280-6491f4d5-fbc2-466e-8d0e-21a71e9dc298.png)

**Comment by TomJinW** [comment]
好的。多谢修改
