### ISSUE TITLE
金图鉴中宝可梦种类不用小字显示

### ISSUE THREAD

**Issue by monkey7581sss888** [TomJinW/PKMN_GSCHS#5]
金图鉴中宝可梦种类不用小字显示

11:439D	416A
11:43B5	8A6A
11:43B7	CB6A
11:43C1	026B
11:43D1	456B
11:43DB	8C6B
11:43E1	BC6B
11:43ED	F96B
11:43FB	3A6C
11:4451	8768
11:4457	B968
11:44C1	FA68

68:6A41
02BF027701A450101103041404330573021A043F05CE012603DA042B024302EE590298043F013E011902BA03DA011A019801995905DB03FD03740466046701D5028701800180018D5002F30439046B500D010003B5037E068503E602F30439046B03DA0293043959082A02ED04930494016004EF59053D042903B80279016B046604670566027C04E25002F30439046B501001000524052504BB034103EE04B903DA0212021302EE59019A014A019B043E097A097A016059073C05ED04BF036850050D011101A4500441000573021A07E2041D097B05F05904660467050C0128049002C5033602AD02AE038F097C039E02935904F302930439034102790374041F011A50028601B1500FF201068D04770983054103DA05FD08CB05E559024107BA061305170524052502D802D95904BB013B04490267026A071705A9028601CC03DA03A103A2011D034F5003050305500A7E04FA06D401B1050E064A5903EE044E04FC0377030C59042903B5076903BA0160028F028A051A04225001BC01BB046B500A5E01039E02930446044703DA01BB01BC590263073204BB033305190160047C026A02DC05ED5905CB028B042B020803DA02D202D35001C105D3500859010349044401F00490590293043902EE032A04F605300466046704FD01A2046F032A059E03DA5906CD086C0769054608960435016003D3033F50091D05D30A91500F2602063B02BA037E011D043F0160033502CE02CF0319043F0490033559050D037C012D083102BA590467081005ED038B094E03DA0197022250

69:6887
0922092301C0500578000467050CF803F505D7020803DA04280802590932046D043E08AE01A859037401A802C2042B02085001C105D350031E00047705ED01C101C10769054603DA032B09A75906A905170523053505D35901A2058305BE0236058204E6052005ED04C501C1051A037403DA50016B092950159808079801FD016009C00479043F011A019402EE590466068E047709C109C20181036808F809C303DA0116023301C05902BC0602043F02E50568029302BA05B3071E03EE043F04CB50

![bgb00007](https://user-images.githubusercontent.com/81839885/175755036-cdb12aeb-1b50-4054-8874-58b83154d8b6.jpg)
![bgb00008](https://user-images.githubusercontent.com/81839885/175755044-365ea493-1c5d-4c19-a7e0-e9e4e02ff92e.jpg)
![bgb00009](https://user-images.githubusercontent.com/81839885/175755047-6532c274-fc95-4e28-8a50-1019930d6803.jpg)
![bgb00010](https://user-images.githubusercontent.com/81839885/175755050-44f81e88-d21e-4291-a228-8a5e6d2f985b.jpg)

银不能使用，需要另外修改

**Comment by TomJinW** [comment]
好的。多谢大佬。包括奖状图片在内的修改已经push到main的最新的pre v1.1的commit中。
