### ISSUE TITLE
取名字不能取英文

### ISSUE THREAD

**Issue by jerrylee4** [TomJinW/PKMN_GSCHS#9]
中文怕影响传后时代
英文因为又对应的码表输入不出来
比如我这个Jerry
JE有码表对应的字
RY也有，无论大小写都输不出来

**Comment by SnDream** [comment]
你在（这个汉化版中）的输入法上看到的“英文字符”只是一种指示符号，和真正的英文版中的英文字母不是一个概念。
硬要说的话，可以试试PKHex修改存档（不过我对这个软件不熟悉）。

**Comment by TomJinW** [comment]
韩版汉化中，所有可以输入的部分本质均为韩文字符。包括「英文字符」的本质是韩文拼写字母。
原韩版不支持英文输入。但是如果是用于「宝可梦虚拟银行传输」的话，所有的中文字符和英文输入符号在传输时会被视为合法韩文，可以直接传输。
<img width="432" alt="截屏2024-10-18 下午5 27 29" src="https://github.com/user-attachments/assets/4ecb54f9-7b2c-4ddd-be69-43dcbd8bdb52">
